import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/** A guest on an event. Mirrors the subset of Google's attendee object we keep;
 * `responseStatus` is "needsAction" | "declined" | "tentative" | "accepted".
 * Shared by the `events` table and the mutation validators that write to it. */
export const attendeeValidator = v.object({
  email: v.string(),
  displayName: v.optional(v.string()),
  responseStatus: v.optional(v.string()),
  organizer: v.optional(v.boolean()),
  self: v.optional(v.boolean()),
  optional: v.optional(v.boolean()),
});

/** A single person Google names on an event — its organizer or its creator.
 * Unlike an attendee this is not a guest list entry, so it carries no RSVP.
 * `self` is set by Google when the person is the calendar this copy lives on,
 * which makes it authoritative: never infer ownership by matching emails. */
export const personValidator = v.object({
  email: v.optional(v.string()),
  displayName: v.optional(v.string()),
  self: v.optional(v.boolean()),
});

/** One event exactly as Google gave it to us, after mapping. Shared by the
 * `events` table and by every action→mutation boundary that pushes a
 * MappedEvent across, so the shape is declared once and cannot drift. */
export const googleEventValidator = v.object({
  googleEventId: v.string(),
  calendarId: v.string(),
  summary: v.optional(v.string()),
  description: v.optional(v.string()),
  location: v.optional(v.string()),
  startMs: v.number(),
  endMs: v.number(),
  allDay: v.boolean(),
  status: v.string(),
  htmlLink: v.optional(v.string()),
  // Google's per-event color override ("1".."11"); absent means the event
  // inherits its calendar's color.
  colorId: v.optional(v.string()),
  // Google's `visibility`: "default" | "public" | "private" | "confidential".
  visibility: v.optional(v.string()),
  // Google's `transparency`: "opaque" (busy) | "transparent" (free).
  transparency: v.optional(v.string()),
  // Guests invited to the event, refreshed by every sync. See attendeeValidator.
  attendees: v.optional(v.array(attendeeValidator)),
  // Google set this when it withheld part of the guest list, so a short
  // `attendees` array is not proof that the list is short.
  attendeesOmitted: v.optional(v.boolean()),
  googleUpdatedMs: v.number(),

  // --- Who controls this event -------------------------------------------
  // `organizer.self` is the ownership test; `creator` differs when someone
  // scheduled on the organizer's behalf, and is only worth showing then.
  organizer: v.optional(personValidator),
  creator: v.optional(personValidator),
  // The three guest permissions. Each is tri-state on purpose: Google omits
  // them at their default, and the defaults disagree — absent guestsCanModify
  // means false, absent guestsCanInviteOthers/SeeOtherGuests mean true. Read
  // them only through lib/permissions.ts, which encodes that.
  guestsCanModify: v.optional(v.boolean()),
  guestsCanInviteOthers: v.optional(v.boolean()),
  guestsCanSeeOtherGuests: v.optional(v.boolean()),
  // Google forbids structural changes to a locked event, whoever you are.
  locked: v.optional(v.boolean()),
  // "default" | "birthday" | "outOfOffice" | "focusTime" | "workingLocation" |
  // "fromGmail". Several of these are generated by Google and reject edits even
  // on a calendar you own.
  eventType: v.optional(v.string()),
  // Set on an expanded instance of a recurring series (we sync with
  // singleEvents=true, so we only ever hold instances, never the master).
  recurringEventId: v.optional(v.string()),
  // The Google Meet URL, when the event has one.
  hangoutLink: v.optional(v.string()),
});

/** The stored row: everything Google told us, plus the local user it belongs
 * to. `userId` is ours alone — it never round-trips to Google. */
export const eventDocValidator = googleEventValidator.extend({
  userId: v.string(),
});

export default defineSchema({
  // One row per user tracking incremental-sync state for Google data.
  // Per-calendar sync tokens live on the `calendars` table.
  syncState: defineTable({
    userId: v.string(),
    contactsSyncToken: v.optional(v.string()),
    lastContactsSyncAt: v.optional(v.number()),
    status: v.union(
      v.literal("idle"),
      v.literal("syncing"),
      v.literal("error"),
    ),
    lastError: v.optional(v.string()),
  }).index("by_user", ["userId"]),

  // One row per Google calendar in the user's CalendarList. Holds display
  // metadata, the user's visibility choice, and the per-calendar sync token.
  calendars: defineTable({
    userId: v.string(),
    googleCalendarId: v.string(),
    summary: v.optional(v.string()),
    summaryOverride: v.optional(v.string()),
    backgroundColor: v.optional(v.string()),
    foregroundColor: v.optional(v.string()),
    primary: v.optional(v.boolean()),
    accessRole: v.optional(v.string()),
    timeZone: v.optional(v.string()),
    // Google's own Calendar UI visibility. This only seeds the local choice
    // when a calendar is first discovered; later local toggles are preserved.
    googleSelected: v.optional(v.boolean()),
    selected: v.boolean(),
    syncToken: v.optional(v.string()),
    lastSyncAt: v.optional(v.number()),
  })
    .index("by_user", ["userId"])
    .index("by_user_and_googleCalendarId", ["userId", "googleCalendarId"]),

  // One row per synced Google Calendar event. See eventDocValidator above.
  events: defineTable(eventDocValidator)
    .index("by_user_and_start", ["userId", "startMs"])
    .index("by_user_and_calendar", ["userId", "calendarId"])
    .index("by_user_and_calendar_and_googleEventId", [
      "userId",
      "calendarId",
      "googleEventId",
    ]),

  // One row per recurring master. Expanded event instances share this rule;
  // keeping it separately avoids duplicating it across every occurrence.
  recurringSeries: defineTable({
    userId: v.string(),
    calendarId: v.string(),
    googleEventId: v.string(),
    recurrence: v.array(v.string()),
    // The instance update time that this rule was fetched against. A newer
    // synced instance invalidates the cache and triggers one master refresh.
    sourceUpdatedMs: v.number(),
  }).index("by_user_and_calendar_and_googleEventId", [
    "userId",
    "calendarId",
    "googleEventId",
  ]),

  // One row per synced Google contact (People API connection).
  contacts: defineTable({
    userId: v.string(),
    resourceName: v.string(),
    displayName: v.optional(v.string()),
    emails: v.array(v.string()),
    phones: v.array(v.string()),
    photoUrl: v.optional(v.string()),
    googleEtag: v.optional(v.string()),
  })
    .index("by_user", ["userId"])
    .index("by_user_and_resourceName", ["userId", "resourceName"]),
});
